floppy/01-install-wget.cmd

This may be a transient error, but the provided wget.exe URL was
throwing HTTP/404 errors, and this was the simplest alternative that
seemed backwards compatible.
Again, this might not be ideal, but was enough to build the boxes again.
Thanks again for the Windows love!

Update WGET_URL to use archive.org.

---

eval-win8x64-enterprise-cygwin.json
eval-win8x64-enterprise.json
floppy/hotfix-KB2842230.bat
win2012-datacenter-cygwin.json
win2012-datacenter.json
win2012-standard-cygwin.json
win2012-standard.json
win8x64-enterprise-cygwin.json
win8x64-enterprise.json
win8x64-pro-cygwin.json
win8x64-pro.json

Hi there! In preparing the [Test Kitchen](http://kitchen.ci) 1.4.0 release which includes support for testing Windows guests, I became all too familiar with [KB2842230](https://support.microsoft.com/en-us/kb/2842230?wa=wsignin1.0). This is a PR that tries to make the affected Windows versions work better out-of-the-box when automated via WinRM.
---
There is a known issue with WinRM ignoring a customized
MaxMemoryPerShellMB on certain default installations of Windows. In this
project, the issue affects the following templates:
* win2012-datacenter-cygwin
* win2012-datacenter
* win2012-standard-cygwin
* win2012-standard
* win8x64-enterprise-cygwin
* win8x64-enterprise
* win8x64-pro-cygwin
* win8x64-pro
This commit adds a floppy-mountable script (hotfix-KB2842230.bat) which
applies the …

Apply Hotfix KB2842230 on Windows 8 & Server 2012 templates.

---

.windows/provisions/Makefile
floppy/01-install-wget.cmd

Btw. the original URL returns an HTML page, which before this patch was then saved as `wget.exe`. This lead to e.g. Windows 7 Pro eval build complain about not being able to execute 16-bit software on 64-bit Windows, which required a user to click "OK". It seems `_download.cmd` then simply tried other download options (like downloading through PowerShell just the way `wget.exe` was originally downloaded) and the build eventually succeeded, but it required the interaction of a user, thus making it not fully unattended.

Fix wget.exe's URL

---

floppy/cygwin.bat
floppy/install-winrm.cmd

`systeminfo` output is localized (bad for `findstr`), `wmic` output is not (good for `findstr`)
Tested on:
- Win 7 x86 Pro SP1 Czech
- Win 7 x64 Enterprise Eval EN
- Win 10 x86 Enterprise Eval EN
- if `fixnetwork.ps1` is not run, winrm indeed fails to launch
- if `findstr` after `wmic` is modified to search for "Windows 9" instead of "Windows 10", winrm does fail to launch (to rule out some typo leading to the line always returning true)
- in the committed form, winrm launches and provisioning starts
- Win 2008R2
- to rule out that `wmic` and `systeminfo` have different behavior between Win 7 and Win 2008 R2 (which are in a way the same version of an OS)
Did not test with cygwin templates, but the command is identical, so it should be fine.
Fixes #45

Detect OS version correctly on non-English Windows

---

floppy/_post_update_install.bat
floppy/update.bat

When update.bat triggers a reboot, scripts following it on the floppy won't execute...mainly zz-start-sshd.cmd.  Added a sub to the VBScript code to run _post_update_install.bat if it exists on the floppy.
This will fix the issue with scripts not running post-install, but could introduce an instance where updates don't trigger a reboot, the _post_update_install.bat file executes, and execution of 00-run-all-scripts.cmd continues on to execute the remaining scripts.  I think as long as the scripts included in _post_update_install.bat are kept to a minimum, it should be fine.

Update.bat reboot fix

---

bin/tweak-json.py

Fix `communicator` and `winrm_timeout` settings name to work with packer 0.10.

Use correct setting names from packer 0.10

---

bin/tweak-json.py

JSON files generated by `tweak-json.py` will not contain trailing whitespace characters anymore.

Fix generated json files to not have trailing whitespace

---

script/cmtool.bat

Updating URL per https://github.com/saltstack/salt-bootstrap/pull/711/commits/05f344c596af9efd7b13b4e31f3e6366140409f3 and bumping the current version to 2015.8.8-2

Update Salt Minion URL and bump current version

---

floppy/install-features.cmd
floppy/remove-features.cmd

* Adds cmd scripts for the installation and removal of Windows Server Features, leveraging Dism in order to accomplish each, on Windows operating systems that include Dism.
* Having this ability is desirable in that removing unused features can significantly reduce final image size, and pre-installation can reduce deployment time.
* Tested successfully as part of a Packer build of Windows Server 2012R2 images.
* The install script defaults to installing the TelnetClient feature, and the removal script defaults to removing the InkAndHandwritingServices feature. I can remove these entries and have it default to performing a no-op if so desired.

Add scripts for feature install/removal

---

floppy/_post_update_install.bat

* Modifies the _post_update_install.bat to allow calling multiple scripts after updates complete (calls all present .cmd scripts with the zz prefix), instead of the static reference to zz-start-sshd.cmd.
* Adds debug logging when the appropriate flag is set.
* Tested successfully as part of a Packer build of Windows Server 2012R2 images.

Allow multiple scripts to be called from post update

---

script/cmtool.bat

The download URLs changed. This will change the format that is passes in since -1 no longer needs to be appended to the normal version string. This also bumps to the latest Chef 12 release and the latest ChefDK. These are MUCH more functional on Windows hosts.
Signed-off-by: Tim Smith <tsmith@chef.io>

Update chef download URL format and default to more recent releases

---

script/cmtool.bat

PUPPET_URL and PUPPET_{32,64}_URL seem to be backwards in the URL construction logic. Results in no puppet install.
Flipped the order to match similar logic for the other CMs. Seems to work.

Fixing puppet variables for URL download.

---

eval-win7x64-enterprise-cygwin.json
eval-win7x64-enterprise-ssh.json
eval-win7x64-enterprise.json
eval-win7x86-enterprise-cygwin.json
eval-win7x86-enterprise-ssh.json
eval-win7x86-enterprise.json

Even when building on modern hardware 1 core and 2 GB is not enough to finish before the timeout happens in packer. There's a service pack and then 251 more updates. We need more ram and CPU
Signed-off-by: Tim Smith <tsmith@chef.io>

Give Win7 more resources so it can install updates in time

---

script/vmtool.bat

This fix should more reliably fix the oracle-cert.cer issue #90 by importing the certificates directly from the Guest Additions iso

Use certificates from VBoxGuestAdditions.iso rather than oracle-cert.cer

---

Makefile
eval-win2016-standard-cygwin.json
eval-win2016-standard-ssh.json
eval-win2016-standard.json
floppy/cygwin.bat
floppy/eval-win2016-standard/Autounattend.xml
floppy/win2016-standard/Autounattend.xml
script/cmtool.bat
tpl/vagrantfile-eval-win2016-standard-cygwin.tpl
tpl/vagrantfile-eval-win2016-standard-ssh.tpl
tpl/vagrantfile-eval-win2016-standard.tpl
tpl/vagrantfile-win2016-standard-cygwin.tpl
tpl/vagrantfile-win2016-standard-ssh.tpl
tpl/vagrantfile-win2016-standard.tpl
win2016-standard-cygwin.json
win2016-standard-ssh.json
win2016-standard.json

Hi,
Sorry for opening this @TwoSlick, didn't know how to get to you.
We've tested the new Windows server 2016 boxes extensively, mostly because we find absolutely impossible to work with windows server 2012 due to the UI. They do work quite well. Tested on Virtualbox and Parallels, not every one of them but most.
https://github.com/fermiumlabs/boxcutter-windows
Also tested on vmware, but without vagrant (unpacking the .box manually)

Windows 2016 By Tim Rupe

---

eval-win2016-standard-cygwin.json
eval-win2016-standard-ssh.json
eval-win2016-standard.json

The default download for Win 2016 eval isos were still set to 2012R2.

Fixed iso url and checksum for win2016 eval

---

script/vmtool.bat

It seems like some changes broke the path where the VirtualBox Guest
Additions were installed via a mounted CD from the Host OS. The changes
look like copy and paste errors from the downloaded ISO path. This
change fixes the paths to be correct. Without this change, the script
produces a WARNING and the guest additions do not get installed.

Fix VBox Guest Additions install

---

Makefile

Having packer fail the build and immediately deleting all work done so far drives me crazy.
Upstream added the `-on-error=ACTION` option for this in https://github.com/hashicorp/packer/pull/3885
This merge request makes that option available via a make variable. Please consider merging!

Allow passing on error behaviour via ON_ERROR make variable.

---

eval-win7x64-enterprise-cygwin.json
eval-win81x64-enterprise.json
win7x64-enterprise-cygwin.json

@dragon788 noticed that there were a few templates where the hyperv-iso builder somehow worked its way into the post-processors. Since it's a builder (and not a post-processor), this resulted in the templates being unable to be validated, and really the templates were just busted.
This PR fixes the two templates that I found with this issue, and also fixed a bunk schema validation in the win7x64-enterprise-cygwin.json template.
This closes PR #192.

Fixed a couple of the templates where the hyperv-iso builder got mixed up with the post-processors

---

win7x64-pro-cygwin.json
win7x64-pro-ssh.json
win7x86-enterprise-cygwin.json
win7x86-enterprise-ssh.json
win7x86-pro-cygwin.json
win7x86-pro-ssh.json
win81x64-enterprise-cygwin.json
win81x64-enterprise-ssh.json

It seems that packer 1.5.1 doesn't support the "ssh_wait_timeout" key in the hyperv-iso builder. This results in Packer not being able to build some of the templates. It's very weird to me that this key isn't supported by the hyperv-iso builder and it smells like a Packer bug.
However, there's no open tickets for this so maybe it was done on purpose. Nonetheless, I collected these into their own PR so that when/if Packer re-introduces this key we can simply revert this PR.
This closes issue #194.

Remove usage of the "ssh_wait_timeout" key from the hyperv-iso builders

---

win7x64-enterprise-ssh.json
win81x64-pro-cygwin.json
win81x64-pro-ssh.json
win81x86-pro-cygwin.json

A couple of templates were missing the ssh_username and ssh_password pair in the hyperv-iso builder. This adds them to the specified templates so that they'll validate and build properly. The win81x86-pro-cygwin template also had the communicator mis-set to "winrm". This PR also fixes that by removing the communicator which should result in packer falling back to ssh.
This closes PR #196.

Added missing keys to a handful of templates

---

win2012r2-standard.json
win2016-standard-cygwin.json
win2016-standard-ssh.json

The win2016-standard-*.json templates had mistakenly used a template variable to define the default value of the "memory" user variable. As template variables can't be used in the definition of user variables, this resulted in the default value for the "memory" variable to be empty. All-in all this results in a failure to validate these templates and requires a user to define the user variable when building.
This PR sets the default value of this user variable to the common value "2048" used by the other win2016-standard templates.
Another thing that this PR fixes is that in the win2012r2-standard.json template the "headless" key is used in the parallels-iso builder. This isn't a valid keyword in the schema from Packer 1.5.1. As a result, this was removed so that template will now …

Fixed the definition of the "memory" user variable in the win2016-standard-*.json templates

---

.gitignore
Makefile
README.md
script/cmtool.bat

This PR is based on PR #180 and supersedes it by splitting up the single-commit into multiple commits for each change to the related files. The core intention of PR #180 is to use Chef's Omnitruck API for determining the CHEF_URL. This allows us to not have to do any work to determine which URL to download Chef's installers from. It also appears that the logic for installing all the Chef-related things is the same, so this PR uses two cases for handling the Chef provisioning in in `scripts/cmtool.bat`.
The first branch is `:omnitruck`. This label determines all the components needed to query the Omnitruck API to find the .msi that needs to be installed. After the request is made, the URL is extracted from the metadata that was returned, and then the `CHEF_URL` variable is assigned with …

Clean up PR #180 which consolidates the chef provisioners and uses the Omnitruck API to fetch the version

---

README.md
script/cmtool.bat

This PR is based on PR #182, and supersedes it. The original intent of the PR is to fix the installation of the SaltStack configuration management tool. Originally we were hardcoding the path to the SaltStack minion url, dowloading, and then installing it. Since then SaltStack has introduced a bootstrap script (https://github.com/saltstack/salt-bootstrap) to install a minion which is used by this PR to automatically determine the url of the correct package to install.
The original PR introduced a new option, `CM_OPTIONS`, that allows the user to customize the options for SaltStack. It was discovered that in `script/cmtool.bat`, all of the configuration tools use their own variable for passing options to their installer (i.e. PUPPET_OPTIONS, CHEF_OPTIONS, etc).
Despite their available, …

Updated installing salt with its bootstrap script, and enabled specifying the CM_OPTIONS for all the configuration management tools

---

script/cmtool.bat

The previous PR #201 which adds support for using salt-bootstrap to install saltstack forgot to include support for windows server 2008 and some of the others. This PR fixes that by extending the platform veresion check to those versions. The major version for those platforms is 5.
This closes issue #204.

Added support for falling back to the saltrepository method int script/cmtool.bat for older versions of windows.

---

script/cmtool.bat

This PR is based on PR #178, and extends it by retaining support for older versions of the puppet cmtool.

Fix URL on puppet cmtool

---

floppy/disablewinupdate.bat

Currently the `floppy/disablewinupdate.bat` script performs a number of actions to completely disable windows updates. One of these actions is to disable the windows updates user interface. This action doesn't interfere with the updates being disabled, but prevents the user from interacting with Windows updates at all. Actually, windows updates will still work with the interface disabled so this doesn't seem to be of the utmost necessity.
Disabling the Windows Updates interface actually has the side-effect of preventing some KBs from being installed, or features from being enabled/disabled. This can interfere with provisioning as you'll have to specifically fix this w/ group policy or registry and then you'll need to enable/restart wuauserv to have access to them again.
This PR leaves the …

Re-enabled the user-interface for updates, whilst still keeping them completely disabled by default

---

win2012r2-standardcore-ssh.json

The `vm_name` field used in the `vmware-iso`, `virtualbox-iso`, and `parallels-iso` builders of the `win2012r2-standardcore-ssh.json` template is actually missing its `-ssh` suffix. This results in a duplicate name of the emitted template and can affect building if the win2012r2-standardcore templates are being built at the same time.
This PR simply updates the `vm_name` field in all the builders so that they contain the `-ssh` suffix similar to the other `-ssh.json` templates.
This closes issue #214.

Fixed the vm_name used by the win2012r2-standardcore-ssh.json template

---

win2012r2-standard-cygwin.json

As a result of merging PR #222, it was discovered that the win2012r2-standard-cygwin.json template is using the wrong file (`floppy/openssh.bat`) in the floppy_files field of the hyperv-iso builder when it should be using `floppy/cygwin.bat` (and `floppy/cygwin.sh`). This results in the hyperv-iso builder for that template installing ssh and not cygwin which is contrary to what the template is supposed to do, and what its other builders are already doing.
This PR fixes the issue by replacing `floppy/openssh.bat` with both `floppy/cygwin.bat` and `floppy/cygwin.sh` which corresponds to what the other builders in the template are doing.
This closes issue #225.

Fix the floppy_files for the hyperv-iso builder belonging to win2012r2-standard-cygwin.json template

---

eval-win7x86-enterprise-ssh.json

As a result of merging PR #222, it was discovered that the eval-win7x86-enterprise-ssh.json template is missing an important file (floppy/openssh.bat) in the floppy_files field that is required to install ssh. This PR fixes that by adding that missing file.
This closes issue #224.

Fix the floppy_files for the hyperv-iso builder belonging to eval-win7x86-enterprise-ssh.json template

---

floppy/01-install-wget.cmd
floppy/_download.cmd
floppy/_packer_config.cmd

Allow disable of BITS.
* Part of #179 so closing #179
Edit `floppy\_packer_config.cmd`:
```
:: Uncomment the following to disable BITS so scripts can fail instead of hanging when
:: BITS doesn't work right.
:: Default: (unset)
:: set DISABLE_BITS=1
```

Add option to disable bits

---

.gitignore
Makefile

* Part of #179 so closing #179
_Note: Does not affect existing `make` commands if `PREFIX` is not set._
Users can clone boxcutter/windows and make user specific copies of Packer templates, scripts and configs they can edit that are ignored by git.  
* Packer `*.json` template files can be symlinks to files in another repo.
* Files in `floppy` and `script` cannot be symlinks but can be links to files in other repos.
This adds flexibility to customize and to easily sync with the upstream repo at any time!
```
cp eval-win10x64-enterprise.json [company].eval-win10x64-enterprise.json
make PREFIX=[company]. [company].[target]
rm -rf output-virtualbox-iso
mkdir -p box/virtualbox
packer build -on-error=cleanup -only=virtualbox-iso -var 'version=1.0.4' -var 'update=false' -var 'headless=false' …
```

User customization without forking

---

floppy/_download.cmd
floppy/bitvisessh.bat
floppy/cygwin.bat
floppy/hotfix-KB2842230.bat
floppy/openssh.bat
floppy/upgrade-wua.bat
script/01-install-handle.cmd
script/cmtool.bat
script/sdelete.bat
script/ultradefrag.bat
script/vagrant.bat
script/vmtool.bat

This PR tampers with all of the scripts so that they explicitly depend on `_download.cmd`. Technically they were doing that before, but they'd always fall back to using Powershell when failing which would also fail because `_download.cmd` was doing the exact same thing. Now we just fail the scripts at their beginning if we're unable to find the cached file and are unable download it.
The `_download.cmd` script was also refactored to change the order of the downloads that are tried. Now we give powershell priority, fallback to `wget.exe`, and then try `bitsadmin.exe` as a last resort. The powershell downloader also requires and sets the minimum security protocol version to Tls 1.2. This is due to the reason that most of tools that we're downloading are now being hosted on a Tls 1.2-only …

Refactor _download.cmd so that Powershell is tried first before falling back to the other download methods.

---

eval-win10x64-enterprise-cygwin.json
eval-win10x64-enterprise-ssh.json
eval-win10x64-enterprise.json
eval-win10x86-enterprise-cygwin.json
eval-win10x86-enterprise-ssh.json
eval-win10x86-enterprise.json

Closes #244 at least for Windows 10. It seems many of the server templates already have this block.

Add prlctl to disable EFI mode

---

floppy/_download.cmd
script/ultradefrag.bat

Part of the provisioning steps for each template downloads ultradefrag v7.0.2 and uses it to defragment the hard disk prior to completion. This is done by using the `floppy/_download.cmd` script to fetch the correct zip file based on the architecture, and then using 7zip to extract and run it. When downloading from sourceforge.net, sourceforget apparently looks at the user agent and uses that to determine whether to return a binary or a webpage with a meta-redirect. This results in some downloaders failing at downloading the archive and getting an html page instead. Specifically, this symptom affects both the powershell and curl fallback downloaders and occurs nearly all the time when using the W7 templates. I imagine this affects bitsadmin in the templates too, but haven't tested that …

Updated the sourceforge.net URI for downloading ultradefrag so that it works properly with all available fallback downloaders

---

floppy/01-install-wget.cmd

Typo in the script causes a failure in a goto statement

Fixed script goto typo
